### ISSUE TITLE
MiFish classifier

### ISSUE THREAD

**Issue by kjledger-NOAA** [kimberlyledger/NBS_eDNA#1]
i am hung up on the classifier needed for taxonomic analysis. i am trying to use classifiers other created specific to the MiFish primer set. see my problems here: https://github.com/kimberlyledger/NBS_eDNA/blob/main/insect_analysis.md

**Comment by DianaBaetscher-NOAA** [comment]
Interesting! It looks like you are trying to download the classifier directly to the VM? Did you try downloading it locally by chance, just to see if that is the limiting step?

**Comment by kjledger-NOAA** [comment]
yes, my first attempt was to download locally but that also failed.  the link appears to be associated with Dropbox.  might there be something blocking the download? i'm going to try downloading at home later to see if that solves anything...

**Comment by kjledger-NOAA** [comment]
downloading the classifier offsite worked :)
