### ISSUE TITLE
Complementary data from BASIS

### ISSUE THREAD

**Issue by DianaBaetscher-NOAA** [kimberlyledger/NBS_eDNA#2]
Matt Callahan introduced me to the BASIS (Bering Arctic Subarctic Integrated Survey) database. This includes the catch data that are complementary to our water samples from 2021 (currently) and in future years (once the database is updated).

Here is a link to an example for downloading catch data from BASIS via AKFIN:
https://htmlpreview.github.io/?https://github.com/MattCallahan-NOAA/basis-catch-spp-lh-0-api/blob/main/basis_catch_spp_lh_0.html

Can you get the data from 2021 and match it up with the station IDs from our eDNA metadata?

**Comment by kjledger-NOAA** [comment]
Here is what 2021 data matches our stations: https://github.com/kimberlyledger/NBS_eDNA/blob/main/get_BASIS_data.md.  Table  at end of markdown
